cn_vat_sh:
  name: VAT Invoice - China
  image:
    # 样板图片的完整尺寸，这是经过旋转后的; 这里的file文件并不参与运算
    w: 1148
    h: 724
    file: ./recognize/cn_vat_sh/image.jpg
  feature:  #特征图片, 尺寸坐标是相对于image. file会参与运算
#    setting of feature.png
#    x: 162
#    y: 14
#    w: 665
#    h: 150
#    file: ./recognize/cn_vat_sh/feature.png
#    option:       # 针对特征匹配的选项, 可选
#      minMatchCount: 20
#      matchDistance: 0.7

#   setting of feature3.png
    x: 20
    y: 21
    w: 1105
    h: 553
    file: ./recognize/cn_vat_sh/feature3.png
    option:       # 针对特征匹配的选项, 可选
      minMatchCount: 30
      matchDistance: 0.7

  rotate: perspective    # 图片旋转的方法，可选有 'line' (按发票进行旋转), 'perspective' (默认，使用特征匹配进行旋转）
  validate:       # 此种图像的验证方式，会把相应信息返回给接口
    roi: DocType  # 相对应的roi的名字，在roi块中定义的
  roi: #roi是感兴趣的区域，需要系统提取的
    Buyer:
      type: text    # text/number/date/currency 这里主要的内容类型。准确的设置值可以提高识别率，如ORC效果。默认text(简体中文)
      x: 216
      y: 163
      w: 432
      h: 120
      ocr: true         # true表示需要调用OCR进行识别, 默认为true
      hide: false       # 是否把这个roi，作为结果返回给接口。例如作为类型检查使用的roi，并不需要返回数据。
      style: blue-font-enhance  # 此ROI的样式，可以增加识别效果。 目前可选值为 'blue-font'（蓝色复印字体），'black-font'（黑色字体）
      line: 4           # 此ROI中，包含的文本行数。默认1。此参数会控制字体大小。
    DocCode:   # fapiao code
      type: number
      x: 160
      y: 60
      w: 205
      h: 40
    DocNumber:  # fapiao number
      type: number
      x: 826
      y: 42
      w: 180
      h: 50
      style: black-font
    DocDate:
      type: date
      x: 912
      y: 110
      w: 185
      h: 37
      style: blue-font-enhance
    Total:
      type: currency
      x: 873
      y: 508
      w: 219
      h: 38
      style: blue-font-enhance
    Items:
      type: text
      x: 50
      y: 300
      w: 270
      h: 180
      style: blue-font-enhance
    ItemsFormat:
      type: text 
      x: 325
      y: 300
      w: 130
      h: 180
      hide: true
      style: blue-font-enhance
    ItemsUnit:
      type: text
      x: 460
      y: 300
      w: 60
      h: 180
    DocType:
      type: number
      x: 164
      y: 51
      w: 209
      h: 41
      hide: true
      style: black-font
      

